version: '3.2'
services:
  jenkins:
    image: brodster22/jenkins-automated-setup:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 8080:8080
    secrets:
      - jenkins-user
      - jenkins-pass
    volumes:
      - type: volume
        source: jenkins_home
        target: /var/jenkins_home
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - jenkins-net


volumes:
  jenkins_home:

networks:
  jenkins-net:
    driver: overlay

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
